### ISSUE TITLE
Error description 

### ISSUE THREAD

**Issue by matthiasbirkicht** [dgelessus/filenav#2]
Dear dgellessus,
thank you for developing the filenav.py
The  litenav.py is working well.
When I try to run the filenav_v1.py or slim.py, there are two ImportErrors occurring:
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/.../Pythonista3/Documents/Examples/filenav/full.py", line 38, in <module>
    import cStringIO as StringIO
ImportError: No module named 'cStringIO'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/.../Pythonista/Documents/Examples/filenav/full.py", line 40, in <module>
    import StringIO
ImportError: No module named 'StringIO'

Does there is a way to fix this issue?
Best regards
Matthias

**Comment by dgelessus** [comment]
It looks like you're trying to run an old version of Filenav with Python 3. Filenav was originally written on Pythonista 1.5, which only supported Python 2 and not Python 3, so the old code was not fully compatible with Python 3. The current version of Filenav works on Python 3, try downloading the current version of the code and then run the `__main__.py` file. That should work with both Python 2 and 3.

The `filenav_v1.py` file contains the old Filenav code before I did some restructuring, so it isn't updated for Python 3. But you can run the script in Pythonista 3 with Python 2, either by long-pressing on the play button and selecting "Run with Python 2.7", or by adding this line at the top of the file:

```python
#!/usr/bin/env python2
```

By the way, I wrote the old `filenav_v1.py` two years ago, and I was not very experienced in Python at that time. Some parts of the code are not ideal, and some things are really badly written. Please don't try to use `filenav_v1.py` as an example of good Python code. `:)`

**Comment by matthiasbirkicht** [comment]
Dear dgelessus,
thank you so much for the fast response. 
Before I started to contact you, I tried out to start the __main__.py. 
It is giving an error message: No module filenav found.
I took the very old file Filenav.py from another place, but there is still an error message:
Cannot import name full.
According to your suggestion I will use the Filenav_v1.py or Filenav.py with Python 2.7.
with an additional script StringIO.py from Phil Christensen.
Thank you for your help and have a happy new year.
Best regards
Matthias

**Comment by dgelessus** [comment]
Ah, I forgot to explain this before, sorry. All of the Filenav `.py` files need to be in a folder called `filenav`, and that folder has to be in the `site-packages` folder (which is in the Pythonista file browser under "Modules & Templates"). Otherwise Python's import system can't find the Filenav code.

It's strange that you need an extra `StringIO.py` script to run the old Filenav in Python 2. The `StringIO` module is a part of Python 2's standard library, so you shouldn't have to install any extra files. I'm not sure, but the "Run with Python 2.7" option might be broken in the current version of Pythonista 3. Try the method using the `#!/usr/bin/env python2` comment instead (see my previous post), as far as I know that works correctly.

**Comment by matthiasbirkicht** [comment]
Dear dgelessus,
thank you for the instructions. During the use of the filenav_v1, I can see, that the library contains a script String.py and StringIO.py. The behavior is not changing, when I put it into folder called filenav and moving it to site-packages. Best regards, Matthias.

**Comment by matthiasbirkicht** [comment]
Dear dgelessus,
Now I am starting to get into the python language. The issue is described by some people as well:
http://stackoverflow.com/questions/13598958/import-modules-from-different-folders
Best regards
Matthias
